// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.warn('[Supabase] Missing environment variables. Auth will not work.');
    return null;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

const noopHandler: ProxyHandler<object> = {
  get(_, prop) {
    if (prop === 'then') return undefined;
    if (typeof prop === 'symbol') return undefined;

    return new Proxy(() => {}, {
      get(_, innerProp) {
        if (innerProp === 'then') return undefined;
        if (typeof innerProp === 'symbol') return undefined;
        if (innerProp === 'getSession') {
          return () => Promise.resolve({ data: { session: null }, error: null });
        }
        if (innerProp === 'signInWithPassword') {
          return () => Promise.resolve({ data: {}, error: { message: 'Supabase not configured' } });
        }
        if (innerProp === 'signUp') {
          return () => Promise.resolve({ data: {}, error: { message: 'Supabase not configured' } });
        }
        if (innerProp === 'signOut') {
          return () => Promise.resolve({ error: null });
        }
        return new Proxy(() => {}, noopHandler);
      },
    });
  },
};

export const supabase: SupabaseClient<Database> = new Proxy({} as SupabaseClient<Database>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    if (!_supabase) {
      return Reflect.get(new Proxy({}, noopHandler), prop, receiver);
    }
    return Reflect.get(_supabase, prop, receiver);
  },
});
